name: iMS3.global
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29abe2'
    - '#ff931e'
    - '#333399'
    - '#2f59b0'
    - '#2d78c3'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
