name: iMS3.global
favicon: null
layout_spectrum: 0.7402943226043135
typography_spectrum: 0.379875835031271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5262223812751472
  lightness: 0.6253010402433574
  saturation: 0.06937721068970859
  rhythmicContrast: 0.7075822614133358
purpose: []
